# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a56Qjo9WknIDOnX1R_0FPW1moAZEaqqA
"""
# pip install --upgrade openai
import os
os.environ["OPENAI_API_KEY"] = "REPLACE_YOUR_KEY_HERE"


from openai import OpenAI
client = OpenAI()

# multiple inputs, one output
completions = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

print(completions.choices[0].message.content)

# one inputs, multiple output
completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "write a sample code for python generative AI on Langchain agents"}
  ],
  n=2
)

print("Sample code 1")
print(completions.choices[0].message.content)
print("Sample code 2")
print(completions.choices[1].message.content)


