# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a56Qjo9WknIDOnX1R_0FPW1moAZEaqqA
"""
# pip install --upgrade openai
import os
os.environ["OPENAI_API_KEY"] = "REPLACE_YOUR_KEY_HERE"


from openai import OpenAI
client = OpenAI()

while True:
    question = input("Give the next question to the AI: ")
    completions = client.chat.completions.create(
      model="gpt-4o-mini",
      messages=[
            {"role": "system", "content": "You are a helpful assistant, act as a expert senior DevOps Engineer and solve user queries related to Kubernetes."},
            {"role": "user", "content": question},
        ]
    )

    print(completions.choices[0].message.content)

    # Get the next question in the loop


