version: '3'
services:
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  prometheus:
    image: bitnami/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000